BEGIN;

-- ============================================================================
-- NewsCollector database schema
-- Recreate from scratch
-- ============================================================================

-- PostgreSQL enums
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'news_category') THEN
        CREATE TYPE news_category AS ENUM ('Geopolitics', 'Gold', 'Crypto', 'Viral', 'Market');
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'signal_action') THEN
        CREATE TYPE signal_action AS ENUM ('Buy', 'Sell', 'Hold');
    END IF;
END$$;

-- ============================================================================
-- Drop old objects if they exist, so the database can be rebuilt cleanly
-- ============================================================================

DROP TABLE IF EXISTS deepseek_analyses CASCADE;
DROP TABLE IF EXISTS news_signals CASCADE;
DROP TABLE IF EXISTS news_articles CASCADE;
DROP TABLE IF EXISTS news_sources CASCADE;

-- ============================================================================
-- news_sources
-- ============================================================================

CREATE TABLE news_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_url TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ux_news_sources_name
    ON news_sources (name);

-- ============================================================================
-- news_articles
-- ============================================================================

CREATE TABLE news_articles (
    id UUID PRIMARY KEY,
    source_id BIGINT NOT NULL,
    source_external_id TEXT NULL,
    source_name TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    url TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    category news_category NOT NULL,
    sentiment_score NUMERIC NULL,
    keywords JSONB NULL,
    raw_payload JSONB NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_news_articles_source_id_news_sources_id
        FOREIGN KEY (source_id)
        REFERENCES news_sources (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_news_articles_published_at
    ON news_articles (published_at DESC);

CREATE INDEX ix_news_articles_source_name_published_at
    ON news_articles (source_name, published_at DESC);

CREATE INDEX ix_news_articles_category_published_at
    ON news_articles (category, published_at DESC);

-- Prevent duplicate article ingestion from the same source and URL
CREATE UNIQUE INDEX ux_news_articles_source_name_url
    ON news_articles (source_name, url)
    WHERE url IS NOT NULL;

-- ============================================================================
-- news_signals
-- ============================================================================

CREATE TABLE news_signals (
    id UUID PRIMARY KEY,
    news_category news_category NOT NULL,
    symbol TEXT NOT NULL,
    action signal_action NOT NULL,
    confidence NUMERIC NOT NULL,
    suggested_price NUMERIC NOT NULL,
    reason TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_news_signals_category_symbol_generated_at
    ON news_signals (news_category, symbol, generated_at DESC);

-- ============================================================================
-- deepseek_analyses
-- ============================================================================

CREATE TABLE deepseek_analyses (
    id UUID PRIMARY KEY,
    category news_category NOT NULL,
    symbol TEXT NOT NULL,
    model_name TEXT NOT NULL,
    summary TEXT NOT NULL,
    confidence NUMERIC NOT NULL,
    verdict TEXT NOT NULL,
    reason TEXT NOT NULL,
    key_points JSONB NULL,
    risk_factors JSONB NULL,
    source_urls JSONB NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    prompt TEXT NULL,
    raw_response TEXT NULL,
    input_fingerprint TEXT NOT NULL,
    input_article_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX ix_deepseek_analyses_category_symbol_generated_at
    ON deepseek_analyses (category, symbol, generated_at DESC);

CREATE UNIQUE INDEX ux_deepseek_analyses_category_symbol_fingerprint
    ON deepseek_analyses (category, symbol, input_fingerprint);

COMMIT;
