using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using NewsCollector.Api.Data;
using NewsCollector.Api.Models;

namespace NewsCollector.Api.Services.DeepSeekAnalysisService.Persistence;

public sealed class DeepSeekAnalysisPersistenceService : IDeepSeekAnalysisPersistenceService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = false
    };

    private readonly NewsDbContext _dbContext;

    public DeepSeekAnalysisPersistenceService(NewsDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task PersistAsync(
        DeepSeekAnalysisResult result,
        IReadOnlyList<string> keyPoints,
        IReadOnlyList<string> riskFactors,
        IReadOnlyList<string> sourceUrls,
        CancellationToken cancellationToken)
    {
        var fingerprint = BuildFingerprint(result);
        var existing = await _dbContext.DeepSeekAnalyses
            .FirstOrDefaultAsync(x => x.Category == result.Category && x.Symbol == result.Symbol && x.InputFingerprint == fingerprint, cancellationToken);

        if (existing is not null)
        {
            return;
        }

        _dbContext.DeepSeekAnalyses.Add(new DeepSeekAnalysisEntity
        {
            Id = result.Id,
            Category = result.Category,
            Symbol = result.Symbol,
            ModelName = result.ModelName,
            Summary = result.Summary,
            Confidence = result.Confidence,
            Verdict = result.Verdict,
            Reason = result.Reason,
            KeyPoints = keyPoints.ToList(),
            RiskFactors = riskFactors.ToList(),
            SourceUrls = sourceUrls.ToList(),
            GeneratedAt = result.GeneratedAt,
            Prompt = BuildPrompt(result),
            RawResponse = JsonSerializer.Serialize(result, JsonOptions),
            InputFingerprint = fingerprint,
            InputArticleCount = sourceUrls.Count
        });

        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task StoreMaturityAsync(
        DeepSeekAnalysisResult result,
        DeepSeekAnalysisMaturityLayer maturity,
        IReadOnlyList<DeepSeekAnalysisOutcome> futureOutcomes,
        CancellationToken cancellationToken)
    {
        var entity = await _dbContext.DeepSeekAnalyses
            .FirstOrDefaultAsync(x => x.Id == result.Id, cancellationToken);

        if (entity is null)
        {
            return;
        }

        entity.MaturityPayloadJson = JsonSerializer.Serialize(maturity, JsonOptions);
        entity.BacktestHistoryJson = JsonSerializer.Serialize(futureOutcomes, JsonOptions);
        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    private static string BuildFingerprint(DeepSeekAnalysisResult result)
    {
        var value = $"{result.Category}|{result.Symbol}|{result.ModelName}|{result.Gap:0.0000}|{result.Signal}|{result.GeneratedAt:O}";
        return Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(value)));
    }

    private static string BuildPrompt(DeepSeekAnalysisResult result)
    {
        return $"Persisted analysis for {result.Category}/{result.Symbol} generated by {result.ModelName}.";
    }
}
